import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "@/context/Providers";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import { Toaster } from "sonner";

const myFont = localFont({
  src: "../../assets/fonts/Satoshi-Variable.ttf",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionWrapper>
    <html lang="en">
      <body className={`${myFont.className} bg-[#09090B] text-white `}>
        <Providers>{children}</Providers>
        <Toaster richColors theme="system" />
      </body>
    </html>
    // </SessionWrapper>
  );
}
